blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on 0x71rex.github.io
    url: https://github.com/0x71rex/0x71rex.github.io/discussions/categories/q-a
    about: Ask a question or request support for 0x71rex.github.io

  - name: Share idea / feature to discuss for 0x71rex.github.io
    url: https://github.com/0x71rex/0x71rex.github.io/discussions/categories/ideas
    about: Share idea / feature to discuss for 0x71rex.github.io

  - name: Connect with 0x71rex (Discord)
    url: https://discord.gg/QeGV2eexJA
    about: Connect with 0x71rex for direct communication